title: Xavier Pedrós # your name (or website title) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b>Applied Economist</b>
  <br><br>
  Keen on quantiative methods for public policy evaluation; and on the intersections between development and public policy. My recent research has centered around ICT and digital markets, in topics of industrial organization and development economics.
  <br><br>
  MSc Economics at Université Catholique de Louvain and BSc Politics at Universitat Pompeu Fabra. I have been Economist at telecoms industry trade body GSMA from Nov 2015 to Aug 2020.
  <br><br>  
  <b><a href="https://docs.google.com/gview?url=https://github.com/xavierpedros/xavierpedros.github.io/raw/master/pdf/CV%202020%20Eng.pdf&embedded=true/" target="_blank">View my CV</a></b>
  
github: is\_project\_page:false

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
