title: Xavier Pedrós # your name (or website title) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Applied Economist
  <br><br>
  Keen on quantiative methods for public policy evaluation; and on the intersections between development and public policy. My recent research, employed at telecoms industry trade body GSMA, has focused around ICT and digital economy, in topics of industrial organization and development economics.
  <br><br>
  <b><a href="https://docs.google.com/gview?url=https://github.com/xavierpedros/xavierpedros.github.io/raw/master/pdf/CV%202020%20Eng.pdf&embedded=true/">View My CV</a><b>
  
github: is\_project\_page:false

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
